export const cartItems = [{
    id: 0,
    imageUri: 'https://i.ibb.co/D98nST1/offer.png',
    title: 'Vinta Backpack',
    price: '$30',
    starsCount: 2.5,
    favorite: true,
    size: 'M',
    color: 'Blue',
}, {
    id: 1,
    imageUri: 'https://i.ibb.co/D98nST1/offer.png',
    title: 'Vinta Backpack',
    price: '$30',
    starsCount: 3.9,
    favorite: true,
    size: 'L',
    color: 'Red',
}, {
    id: 2,
    imageUri: 'https://i.ibb.co/D98nST1/offer.png',
    title: 'Vinta Backpack',
    price: '$30',
    starsCount: 1.6,
    favorite: false,
    size: 'XL',
    color: 'White',
}, {
    id: 3,
    imageUri: 'https://i.ibb.co/D98nST1/offer.png',
    title: 'Vinta Backpack',
    price: '$30',
    starsCount: 4.5,
    favorite: true,
    size: 'M',
    color: 'Black',
}, {
    id: 4,
    imageUri: 'https://i.ibb.co/D98nST1/offer.png',
    title: 'Vinta Backpack',
    price: '$30',
    starsCount: 3,
    favorite: false,
    size: 'S',
    color: 'Yellow',
}, {
    id: 5,
    imageUri: 'https://i.ibb.co/D98nST1/offer.png',
    title: 'Vinta Backpack',
    price: '$30',
    starsCount: 2.4,
    favorite: true,
    size: 'L',
    color: 'Pink',
}];
