export const homeData_en = [{
    id: 0,
    category:'lenses',
    tabName_en: 'Lenses',
    tabName_ar: 'عدسات',
    productTypes_en: ['Brand', 'Offers', 'Deals'],
    productTypes_ar: ['ماركة', 'عروض', 'صفقات'],
    list: [{
        id: 0,
        name_en: 'optica',
        name_ar: 'بصريات',
        imageUrl: 'https://i.ibb.co/kJtV2By/download.jpg',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Offers'],
        types_ar: ['عروض'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 2.5,
        size: 'M',
        price: 100,
        offerValue: 25,
    }, {
        id: 1,
        name_en: 'Women Leather Bag1',
        name_ar: 'حقيبة جلد نسائية1',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Offers'],
        types_ar: ['عروض'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3,
        size: 'M',
        price: 280,
        offerValue: 25,
    }, {
        id: 2,
        name_en: 'Women Leather Bag2',
        name_ar: 'حقيبة جلد نسائية2',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Brand', 'Offers'],
        types_ar: ['ماركة', 'عروض'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.5,
        size: 'M',
        price: 220,
        offerValue: 25,
    }, {
        id: 3,
        name_en: 'Orange Summer Dress',
        name_ar: 'فستان برتقالي صيفي',
        imageUrl: 'https://i.ibb.co/JHKyPSy/Capture.png',
        images: ['https://i.ibb.co/JHKyPSy/Capture.png', 'https://i.ibb.co/JHKyPSy/Capture.png'],
        types_en: ['Deals'],
        types_ar: ['صفقات'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.7,
        size: 'M',
        price: 300,
        offerValue: 25,
    }, {
        id: 4,
        name_en: 'Women Leather Bag3',
        name_ar: 'حقيبة جلد نسائية3',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 1.7,
        size: 'M',
        price: 600,
        offerValue: 25,
        offerTime: 2000,
    }, {
        id: 5,
        name_en: 'Women Leather Bag4',
        name_ar: 'حقيبة جلد نسائية4',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 2.9,
        size: 'M',
        price: 30,
        offerValue: 450,
        offerTime: 2000,
    }, {
        id: 6,
        name_en: 'Women Leather Bag5',
        name_ar: 'حقيبة جلد نسائية5',
        imageUrl: 'https://i.ibb.co/kJtV2By/download.jpg',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Brand'],
        types_ar: ['ماركة'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.3,
        size: 'M',
        price: 250,
        offerValue: 25,
    }, {
        id: 7,
        name_en: 'Women Leather Bag6',
        name_ar: 'حقيبة جلد نسائية6',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.7,
        size: 'M',
        price: 190,
        offerValue: 25,
    }, {
        id: 8,
        name_en: 'Women Leather Bag7',
        name_ar: 'حقيبة جلد نسائية7',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.9,
        size: 'M',
        price: 160,
        offerValue: 25,
    }, {
        id: 9,
        name_en: 'LENSE ME1',
        name_ar: 'عدسات1',
        imageUrl: 'https://i.ibb.co/Fqc5J8R/offer1.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 1.7,
        size: 'M',
        price: 120,
        offerValue: 25,
        type: 'offer',
        buyNumber: 2,
        freeNumber: 1,
    }, {
        id: 10,
        name_en: 'LENSE ME2',
        name_ar: 'عدسات2',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 2.9,
        size: 'M',
        price: 150,
        offerValue: 25,
        offerTime: 2000,
        type: 'sale',
        discount: 20
    }, {
        id: 11,
        name_en: 'AMARA',
        name_ar: 'أمارا',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.3,
        size: 'M',
        price: 200,
        offerValue: 25,
        offerTime: 2000,
    }, {
        id: 12,
        name_en: 'AMARA',
        name_ar: 'أمارا',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 5,
        size: 'M',
        price: 300,
        offerValue: 25,
        offerTime: 2000,
    }]
}, /*{
    id: 1,
    category:'skinCare',
    tabName_en: 'Skin Care',
    tabName_ar: 'العناية بالبشرة',
    productTypes_en: ['Brand', 'Offers', 'Deals'],
    productTypes_ar: ['ماركة', 'عروض', 'صفقات'],
    list: [{
        id: 20,
        name_en: 'optica',
        name_ar: 'بصريات',
        imageUrl: 'https://i.ibb.co/kJtV2By/download.jpg',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Offers'],
        types_ar: ['عروض'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.5,
        size: 'M',
        price: 1000,
        offerValue: 25,
    }, {
        id: 21,
        name_en: 'Women Leather Bag1',
        name_ar: 'حقيبة جلد نسائية1',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Offers'],
        types_ar: ['عروض'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.5,
        size: 'M',
        price: 123,
        offerValue: 25,
    }, {
        id: 22,
        name_en: 'Women Leather Bag2',
        name_ar: 'حقيبة جلد نسائية2',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Brand', 'Offers'],
        types_ar: ['ماركة', 'عروض'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.5,
        size: 'M',
        price: 355,
        offerValue: 25,
    }, {
        id: 23,
        name_en: 'Orange Summer Dress',
        name_ar: 'فستان برتقالي صيفي',
        imageUrl: 'https://i.ibb.co/JHKyPSy/Capture.png',
        images: ['https://i.ibb.co/JHKyPSy/Capture.png', 'https://i.ibb.co/JHKyPSy/Capture.png'],
        types_en: ['Deals'],
        types_ar: ['صفقات'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.7,
        size: 'M',
        price: 3006,
        offerValue: 25,
    }, {
        id: 24,
        name_en: 'Women Leather Bag3',
        name_ar: 'حقيبة جلد نسائية3',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.7,
        size: 'M',
        price: 4343,
        offerValue: 25,
        offerTime: 2000,
    }, {
        id: 25,
        name_en: 'Women Leather Bag4',
        name_ar: 'حقيبة جلد نسائية4',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.9,
        size: 'M',
        price: 305,
        offerValue: 450,
        offerTime: 2000,
    }, {
        id: 26,
        name_en: 'Women Leather Bag5',
        name_ar: 'حقيبة جلد نسائية5',
        imageUrl: 'https://i.ibb.co/kJtV2By/download.jpg',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Brand'],
        types_ar: ['ماركة'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.3,
        size: 'M',
        price: 2520,
        offerValue: 25,
    }, {
        id: 27,
        name_en: 'Women Leather Bag6',
        name_ar: 'حقيبة جلد نسائية6',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 5.7,
        size: 'M',
        price: 343,
        offerValue: 25,
    }, {
        id: 28,
        name_en: 'Women Leather Bag7',
        name_ar: 'حقيبة جلد نسائية7',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 2.9,
        size: 'M',
        price: 3222,
        offerValue: 25,
    }, {
        id: 29,
        name_en: 'LENSE ME1',
        name_ar: 'عدسات1',
        imageUrl: 'https://i.ibb.co/Fqc5J8R/offer1.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 2.7,
        size: 'M',
        price: 1220,
        offerValue: 25,
        type: 'offer',
        buyNumber: 2,
        freeNumber: 1,
    }, {
        id: 220,
        name_en: 'LENSE ME2',
        name_ar: 'عدسات2',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 1.9,
        size: 'M',
        price: 15220,
        offerValue: 25,
        offerTime: 2000,
        type: 'sale',
        discount: 20
    }, {
        id: 211,
        name_en: 'LENSE ME2',
        name_ar: 'عدسات2',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.3,
        size: 'M',
        price: 2200,
        offerValue: 25,
        offerTime: 2000,
        quantity: 1
    }, {
        id: 212,
        name_en: 'AMARA',
        name_ar: 'أمارا',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 5,
        size: 'M',
        price: 30078,
        offerValue: 25,
        offerTime: 2000,
    }]*/
// },
/*{
    id: 2,
    category:'makeUp',
    tabName: 'Makeup',
    tabName_ar: 'مكياج',
    productTypes_en: ['Brand', 'Offers', 'Deals'],
    productTypes_ar: ['ماركة', 'عروض', 'صفقات'],
    list: [{
        id: 30,
        name_en: 'optica',
        name_ar: 'بصريات',
        imageUrl: 'https://i.ibb.co/kJtV2By/download.jpg',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Offers'],
        types_ar: ['عروض'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 2.5,
        size: 'M',
        price: 1000,
        offerValue: 25,
    }, {
        id: 31,
        name_en: 'Women Leather Bag1',
        name_ar: 'حقيبة جلد نسائية1',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Offers'],
        types_ar: ['عروض'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3,
        size: 'M',
        price: 7655,
        offerValue: 25,
    }, {
        id: 32,
        name_en: 'Women Leather Bag2',
        name_ar: 'حقيبة جلد نسائية2',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Brand', 'Offers'],
        types_ar: ['ماركة', 'عروض'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.5,
        size: 'M',
        price: 4888,
        offerValue: 25,
    }, {
        id: 33,
        name_en: 'Orange Summer Dress',
        name_ar: 'فستان برتقالي صيفي',
        imageUrl: 'https://i.ibb.co/JHKyPSy/Capture.png',
        images: ['https://i.ibb.co/JHKyPSy/Capture.png', 'https://i.ibb.co/JHKyPSy/Capture.png'],
        types_en: ['Deals'],
        types_ar: ['صفقات'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.7,
        size: 'M',
        price: 30760,
        offerValue: 25,
    }, {
        id: 34,
        name_en: 'Women Leather Bag3',
        name_ar: 'حقيبة جلد نسائية3',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 1.7,
        size: 'M',
        price: 7533,
        offerValue: 25,
        offerTime: 2000,
    }, {
        id: 35,
        name_en: 'Women Leather Bag4',
        name_ar: 'حقيبة جلد نسائية4',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 2.9,
        size: 'M',
        price: 76666,
        offerValue: 450,
        offerTime: 2000,
    }, {
        id: 36,
        name_en: 'Women Leather Bag5',
        name_ar: 'حقيبة جلد نسائية5',
        imageUrl: 'https://i.ibb.co/kJtV2By/download.jpg',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Brand'],
        types_ar: ['ماركة'],
        layout: 'horizontal',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.3,
        size: 'M',
        price: 6444,
        offerValue: 25,
    }, {
        id: 37,
        name_en: 'Women Leather Bag6',
        name_ar: 'حقيبة جلد نسائية6',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg', 'https://i.ibb.co/kJtV2By/download.jpg'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 3.7,
        size: 'M',
        price: 19650,
        offerValue: 25,
    }, {
        id: 38,
        name_en: 'Women Leather Bag7',
        name_ar: 'حقيبة جلد نسائية7',
        imageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
        images: ['https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png', 'https://i.ibb.co/F44ZT5T/offer.png'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'vertical',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.9,
        size: 'M',
        price: 1605,
        offerValue: 25,
    }, {
        id: 39,
        name_en: 'LENSE ME1',
        name_ar: 'عدسات1',
        imageUrl: 'https://i.ibb.co/Fqc5J8R/offer1.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Brand'],
        types_ar: ['صفقات', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 1.7,
        size: 'M',
        price: 3222,
        offerValue: 25,
        type: 'offer',
        buyNumber: 2,
        freeNumber: 1,
    }, {
        id: 310,
        name_en: 'LENSE ME2',
        name_ar: 'عدسات2',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 2.9,
        size: 'M',
        price: 4333,
        offerValue: 25,
        offerTime: 2000,
        type: 'sale',
        discount: 20
    }, {
        id: 311,
        name_en: 'LENSE ME2',
        name_ar: 'عدسات2',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 4.3,
        size: 'M',
        price: 433,
        offerValue: 25,
        offerTime: 2000,
    }, {
        id: 312,
        name_en: 'AMARA',
        name_ar: 'أمارا',
        imageUrl: 'https://i.ibb.co/ZJp6LyM/offer0.png',
        images: ['https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png', 'https://i.ibb.co/Fqc5J8R/offer1.png'],
        types_en: ['Deals', 'Offers', 'Brand'],
        types_ar: ['صفقات', 'عروض', 'ماركة'],
        layout: 'small',
        description_en: 'Ye to misery wisdom plenty polite to as. Prepared interest proposal it he exercise. My wishing an in attempt ferrars.',
        description_ar: 'هذا المنتج مصنوع وفق معايير عالية الجودة.',
        starsCount: 5,
        size: 'M',
        price: 30330,
        offerValue: 25,
        offerTime: 2000,
    }]*/
// }
];
