export const offerVerticalCards = [{
    id: 0,
    productName: 'Women Leather Bag',
    productImageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
    offerValue: 20,
    productPrice: 1000,
    favorite: true,
    isAddedToCart: false,
}, {
    id: 1,
    productName: 'Women Leather Bag',
    productImageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
    offerValue: 10,
    productPrice: 400,
    favorite: true,
    isAddedToCart: false,
    offerTime: 100000,
}, {
    id: 2,
    productName: 'Women Leather Bag',
    productImageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
    offerValue: 20,
    productPrice: 1000,
    favorite: false,
    offerTime: 100000,
}, {
    id: 3,
    productName: 'Women Leather Bag',
    productImageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
    offerValue: 30,
    productPrice: 500,
    favorite: true,
    isAddedToCart: false,
}, {
    id: 4,
    productName: 'Women Leather Bag',
    productImageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
    offerValue: 4,
    productPrice: 1000,
    favorite: false,
    isAddedToCart: true,
    offerTime: 100000,
}, {
    id: 5,
    productName: 'Women Leather Bag',
    productImageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
    offerValue: 6,
    productPrice: 400,
    favorite: true,
    isAddedToCart: false,
}, {
    id: 6,
    productName: 'Women Leather Bag',
    productImageUrl: 'https://i.ibb.co/F44ZT5T/offer.png',
    offerValue: 10,
    productPrice: 500,
    favorite: false,
    isAddedToCart: true,
    offerTime: 100000,
},];
